version: '3'
services:
  app:
    image: eclipse-temurin:11
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./:/work
    working_dir: /work
    tty: true
    depends_on:
      - db
    command: ./gradlew clean bootRun
  db:
    container_name: graphql_pgsql
    image: postgres:14
    restart: always
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testuser
      POSTGRES_DB: sampledb
      DATABASE_HOST: localhost
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
