spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/sampledb
    username: postgres
    password: testuser
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 10
  graphql:
    graphiql:
      enabled: true
      path: /graphiql

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*.xml